CREATE TABLE IF NOT EXISTS `nsi_eis_organizations_223` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Идентификатор (внутр)',
  `eis_guid` varchar(36) NOT NULL DEFAULT '' COMMENT 'Идентификатор позиции в информационном пакете ',
  `eis_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'Индивидуальный код организации ',
  `eis_updateDate` datetime NOT NULL COMMENT 'Дата и время изменения данных об организации в ЕСИА',
  `nameFull` varchar(1000) NOT NULL DEFAULT '' COMMENT 'Наименование ',
  `nameShort` varchar(500) NOT NULL DEFAULT '' COMMENT 'Сокращенное наименование ',
  `region` int(11) NOT NULL COMMENT 'Регион',
  `inn` varchar(12) NOT NULL DEFAULT '' COMMENT 'ИНН ',
  `kpp` varchar(9) NOT NULL DEFAULT '' COMMENT 'КПП ',
  `ogrn` varchar(13) NOT NULL DEFAULT '' COMMENT 'ОГРН ',
  `okfs` varchar(2) NOT NULL DEFAULT '' COMMENT 'Код ОКФС',
  `okopf` varchar(5) NOT NULL DEFAULT '' COMMENT 'Код ОКОПФ ',
  `okato` varchar(11) NOT NULL DEFAULT '' COMMENT 'Код ОКАТО',
  `oktmo` varchar(11) NOT NULL DEFAULT '' COMMENT 'Код ОКТМО',
  `okpo` varchar(10) NOT NULL DEFAULT '' COMMENT 'Код ОКПО ',
  `legalAddress` varchar(2000) NOT NULL DEFAULT '' COMMENT 'Юридический адрес',
  `postalAddress` varchar(2000) NOT NULL DEFAULT '' COMMENT ' Почтовый адрес ',
  `type` varchar(2000) NOT NULL DEFAULT '' COMMENT 'Тип организации ',
  `timeZone` varchar(50) NOT NULL COMMENT 'Cмещение относительно UTC',
  `contactFIO` varchar(600) NOT NULL DEFAULT '' COMMENT 'ФИО контактного лица',
  `contactEmail` varchar(300) NOT NULL DEFAULT '' COMMENT 'Email контактного лица',
  `orgPhone` varchar(300) NOT NULL DEFAULT '' COMMENT 'Телефон ',
  `orgFax` varchar(300) NOT NULL DEFAULT '' COMMENT 'Факс ',
  `orgEmail` varchar(300) NOT NULL DEFAULT '' COMMENT 'Email ',
  `orgWebsite` varchar(300) NOT NULL DEFAULT '' COMMENT 'URL  веб-сайта',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `eis_guid` (`eis_guid`) USING BTREE,
  KEY `eis_code` (`eis_code`) USING BTREE,
  KEY `eis_updateDate` (`eis_updateDate`) USING BTREE,
  KEY `region` (`region`) USING BTREE,
  KEY `inn` (`inn`) USING BTREE,
  KEY `kpp` (`kpp`) USING BTREE,
  KEY `oktmo` (`oktmo`) USING BTREE,
  KEY `okato` (`okato`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='Справочник организации с сайта ЕИС по 223 ФЗ';
